# Travis CI (http://travis-ci.org/) is a continuous integration service for
# open source projects. This file configures it to run unit tests.

language: go

go:
    - 1.2
    - 1.3
    - 1.4

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install:
    - go get -d -t -v ./...
    - go build -v ./...

script:
    - $HOME/gopath/bin/goveralls -service=travis-ci
